{"uuid": "29ac779f-cbb0-423f-b0e7-df9fef9e7b51", "children": ["4ffff454-2dc1-455d-a018-afd59775fbfd", "fb441c29-14d7-44a0-8793-c6d60cf924ec", "0c91bad3-5372-4e4f-a9dc-fd04598bd38b", "ab45e68f-bc5c-4576-aa85-374b2564d061", "eadbf024-760e-472d-a0e5-0e5b2a5f99af", "72c11f7f-eae5-4af1-991b-29a9eaa5ea00", "fe2a2929-7dad-4f37-9580-12d7ebe435f1", "56389937-2122-4628-8e07-80c95c0cba27", "f81fe654-7999-45ac-aba5-e97bfe41ddcd", "8fb3006c-6bfa-475c-b060-6756fc8cdb9b", "c78ea6f3-8ad3-4444-b2a3-3fe3861cbaf3"], "befores": [{"name": "authenticated_user", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: 'url' must be a string\n  (Session info: chrome=131.0.6778.205)\nStacktrace:\n\tGetHandleVerifier [0x0083EC13+23731]\n\t(No symbol) [0x007CC394]\n\t(No symbol) [0x006ABE63]\n\t(No symbol) [0x0072BF46]\n\t(No symbol) [0x00711E5C]\n\t(No symbol) [0x0072B46E]\n\t(No symbol) [0x00711BF6]\n\t(No symbol) [0x006E3F35]\n\t(No symbol) [0x006E4EBD]\n\tGetHandleVerifier [0x00B1F0D3+3039603]\n\tGetHandleVerifier [0x00B32DEA+3120778]\n\tGetHandleVerifier [0x00B2B592+3089970]\n\tGetHandleVerifier [0x008D43B0+635984]\n\t(No symbol) [0x007D4DCD]\n\t(No symbol) [0x007D2068]\n\t(No symbol) [0x007D2205]\n\t(No symbol) [0x007C4FD0]\n\tBaseThreadInitThunk [0x7710FCC9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77C2809E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77C2806E+238]\n\n", "trace": "  File \"C:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Dell\\Desktop\\Ambition hire file\\Ambition hire\\conftest.py\", line 142, in authenticated_user\n    login.get(env)\n  File \"C:\\Users\\Dell\\Desktop\\Ambition hire file\\Ambition hire\\Pages_Candidate\\base_page.py\", line 20, in get\n    self.driver.get(url)\n  File \"C:\\Users\\Dell\\AppData\\Roaming\\Python\\Python312\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 357, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Dell\\AppData\\Roaming\\Python\\Python312\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Dell\\AppData\\Roaming\\Python\\Python312\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1735888323361, "stop": 1735888323364}], "start": 1735888323361, "stop": 1735888323978}