{"uuid": "938ecfd2-cf9c-47d2-bc39-445329150b23", "children": ["c4e8fe12-cdf6-4cfb-be15-4d2e86b0c5af"], "befores": [{"name": "driver", "status": "failed", "statusDetails": {"message": "Failed: Chrome driver initialization failed: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n", "trace": "  File \"C:\\Users\\AppzLogic\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AppzLogic\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AppzLogic\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AppzLogic\\Desktop\\Ambitionhire\\conftest.py\", line 109, in driver\n    pytest.fail(f\"Chrome driver initialization failed: {e}\")\n  File \"C:\\Users\\AppzLogic\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\outcomes.py\", line 198, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1723096320797, "stop": 1723096394488}], "start": 1723096320797, "stop": 1723096395133}